name: Deployment Workflow
env:
  REGION: ap-south-1
  APP_NAME: demo-app
  ENV_NAME: demo-env
on:
  push:
    branches: ["main"]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: install dependencies
        run: npm install
      - name: run tests
        run: npm test
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ env.APP_NAME}}
          environment_name: ${{ env.ENV_NAME}}
          version_label: v-${{ github.run_number }}
          region: ${{ env.REGION }}